project:
  type: website

website:
  title: |
    Arte, Sociedade e\
    Interpretações do Brasil
    
  navbar:
    right:
      - href: pessoas.qmd
        text: Pessoas
      - href: projetos.qmd
        text: Projetos
      - href: publicacoes.qmd
        text: Publicações
      - href: eventos.qmd
        text: Eventos
      - href: contato.qmd
        text: Contato
    
     
  page-footer: |
    <div style="display: flex; justify-content: space-between; align-items: center;">
      <span>Copyright 2022</span>
      <img src="images/sol.png" alt="SOL" style="height: 50px;">
      <span>
        <a href="https://www.unb.br">UnB</a> | 
        <a href="https://www.ppgsol.unb.br">PPGSOL</a>
      </span>
    </div>

execute:
  freeze: auto  
format:
  html:
    theme: litera
    mainfont: heuristica
    css: styles.css
    toc: true
    lang: pt-BR
    text-align: justify;
    

        



