project:
  type: website

website:
  title: |
    Arte, Sociedade e\
    Interpretações do Brasil
    
  navbar:
    right:
      - href: pessoas.qmd
        text: Pessoas
      - href: projetos.qmd
        text: Projetos
      - href: publicacoes.qmd
        text: Publicações
      - href: eventos.qmd
        text: Eventos
      - href: contato.qmd
        text: Contato

  sidebar:
    style: floating
    contents:
      - section: "Agenda"
        contents:        
          - text: "Seminários"
          - image: /images/samico.png 
            href: eventos/seminarios_2024_2.qmd
          - text: "Disciplinas"
            href: eventos/Disciplinas.qmd
          

  page-footer:
    left: "Copyright 2022"
    right: 
      - text: UnB
        href: https://www.unb.br
      - text: PPGSOL
        href: https://www.ppgsol.unb.br

execute:
  freeze: auto  

format:
  html:
    theme: litera
    mainfont: heuristica
    css: styles.css
    toc: true
    lang: pt-BR
    text-align: justify;
        



